# values.yaml

alertmanager:
  enabled: false

server:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

  persistentVolume:
    enabled: true
    size: 1Gi
    storageClass: standard

  service:
    type: ClusterIP
    port: 9090

  serviceMonitor:
    selfMonitor: true

  config:
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']


