# helm/prometheus/values.yaml

server:
  global:
    scrape_interval: 15s

  service:
    type: LoadBalancer

  persistence:
    enabled: true
    size: 8Gi
    storageClass: standard

  securityContext:
    runAsUser: 1000
    fsGroup: 2000

  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
