apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: k8s.io/minikube-hostpath  # Minikube's default provisioner
volumeBindingMode: Immediate  # This is the default behavior for Minikube
