persistence:
  enabled: true
  size: 8Gi
  storageClassName: default

adminUser: admin
adminPassword: admin
service:
  type: LoadBalancer

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server
      access: proxy
      isDefault: true

# Add PostgreSQL database configuration
env:
  GF_DATABASE_TYPE: postgres
  GF_DATABASE_HOST: my-postgresql.default.svc.cluster.local:5432
  GF_DATABASE_NAME: mydatabase
  GF_DATABASE_USER: admin
  GF_DATABASE_PASSWORD: mypassword
