apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-user-list-namespaces
subjects:
- kind: ServiceAccount
  name: test-user
  namespace: default
roleRef:
  kind: ClusterRole
  name: list-namespaces-role
  apiGroup: rbac.authorization.k8s.io