apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-creator
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "get", "list"]  # Adjust permissions as per your requirements
