apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-user-rolebinding
subjects:
- kind: ServiceAccount
  name: test-user
roleRef:
  kind: Role
  name: namespace-creator  # Use the name of the Role created above
  apiGroup: rbac.authorization.k8s.io