apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-microservice
  template:
    metadata:
      labels:
        app: python-microservice
    spec:
      containers:
      - name: python-microservice-container
        image: docker.io/c00perd0n/python-microservice:v1
        ports:
        - containerPort: 5000
