name: Deploy to Local Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Kubernetes context
      run: |
        kubectl config use-context minikube
        kubectl config current-context

    - name: Set up Helm
      run: |
        helm repo add stable https://charts.helm.sh/stable
        helm repo update

    - name: Deploy Prometheus
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
        helm upgrade --install prometheus prometheus-community/prometheus -f helm/prometheus/values.yaml --namespace monitoring --create-namespace

    - name: Deploy Grafana
      run: |
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update
        helm upgrade --install grafana grafana/grafana -f helm/grafana/values.yaml --namespace monitoring

    - name: Check Helm Releases
      run: |
        helm list -n monitoring

    - name: Check Pods in Monitoring Namespace
      run: |
        kubectl get pods -n monitoring

    - name: Check Events in Monitoring Namespace
      run: |
        kubectl get events -n monitoring
