name: Deploy Prometheus to Kind (local)

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull request events to the main branch

jobs:
  deploy_prometheus:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install Terraform with elevated privileges
      - name: Install Terraform and Terragrunt
        run: |
          Start-Process powershell -ArgumentList "Invoke-WebRequest -Uri 'https://releases.hashicorp.com/terraform/0.14.9/terraform_0.14.9_windows_amd64.zip' -OutFile 'terraform.zip'; Expand-Archive -Path 'terraform.zip' -DestinationPath 'C:\Program Files\terraform'; $env:Path += ';C:\Program Files\terraform'; terraform --version" -Verb RunAs
          Invoke-WebRequest -Uri 'https://github.com/gruntwork-io/terragrunt/releases/download/v0.34.0/terragrunt_windows_amd64.exe' -OutFile 'C:\Program Files\terragrunt.exe'; $env:Path += ';C:\Program Files\'; terragrunt --version
      # Verify Terraform installation
      - name: Verify Terraform installation
        run: terraform --version

      # Log into your local Kubernetes cluster (Kind)
      - name: Configure Kubernetes context
        run: |
          kind export kubeconfig --name=kind-roth-prod
          kubectl config use-context kind-roth-prod

      # Debugging: List contents of root directory
      - name: List contents of root directory
        run: |
          Get-ChildItem -Path . -Force

      # Debugging: List contents of environments/dev directory
      - name: List contents of environments/dev directory
        run: |
          Get-ChildItem -Path .\rt-observability\environments\dev -Force

      # Initialize Terraform (install providers, modules, etc.)
      - name: Initialize Terraform
        run: |
          cd .\rt-observability\environments\dev  # Adjust to your environment directory
          ls  # List contents to verify directory contents
          terraform init

      # Initialize Terraform (install providers, modules, etc.)
      - name: Initialize Terraform
        run: |
          cd .\rt-observability\modules\prometheus  # Adjust to your environment directory
          ls  # List contents to verify directory contents
          terraform init
    
      # Apply Terraform changes (deploy Prometheus)
      - name: Deploy Prometheus with Terraform
        run: |
          cd .\rt-observability\environments\dev  # Adjust to your environment directory
          ls  # List contents to verify directory contents
          terraform apply -auto-approve -var-file="./variables.tfvars"

      # Capture output or any further integration steps (optional)
      - name: Capture Prometheus endpoint
        run: |
          cd .\rt-observability\environments\dev  # Adjust to your environment directory
          ls  # List contents to verify directory contents
          terraform output prometheus_endpoint > prometheus_endpoint.txt
          Get-Content .\prometheus_endpoint.txt  # Example: Display output

      # Clean up (optional: destroy resources after testing)
      - name: Destroy Prometheus deployment
        if: ${{ github.event_name == 'pull_request' }}  # Optional: Only destroy on PR events
        run: |
          cd .\rt-observability\environments\dev  # Adjust to your environment directory
          ls  # List contents to verify directory contents
          terraform destroy -auto-approve
