name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout grafana-tf repository
      uses: actions/checkout@v2
      with:
        repository: c00perdon/grafana-tf
        ref: main  # Adjust if you want to use a different branch

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.11

    - name: Terraform Init
      run: |
        cd grafana-tf
        terraform init

    - name: Terraform Apply
      run: |
        cd grafana-tf
        terraform apply -auto-approve
